name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: v12.18.3
    - run: | 
        yarn
        yarn lint
        yarn test
